import datetime


MIN_NUMBER_OF_PARTICIPANT = 2
MAX_NUMBER_OF_PARTICIPANT = 100
MAX_MEETING_DURATION_IN_MINUTE = 300
MIN_MEETING_DURATION_IN_MINUTE = 10
EARLIEST_MEETING_START = datetime.time(7, 00)
LATEST_MEETING_END = datetime.time(19, 00)
